# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))



# -- Project information -----------------------------------------------------

project = u'Kobiton Documentation'
copyright = u'2024, Kobiton'
author = u'Shanika Wickramasinghe'

# The short X.Y version
version = '0.0.1'
# The full version, including alpha/beta/rc tags
release = version


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.viewcode', 
    'sphinx_tabs.tabs', 
    'sphinxcontrib.openapi',
    #'sphinx_copybutton',
]

#'sphinx_copybutton'

sphinx_tabs_disable_tab_closing = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinxawesome_theme'
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
from sphinxawesome_theme import LinkIcon

html_theme_options = {
    # 'style_external_links': False, 
    # 'logo_only': True,
    "awesome_external_links": False,
    "breadcrumbs_separator":">",
    "extra_header_link_icons": {
        "GitHub": LinkIcon(
            icon="""<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24" version="1.1" class="github-icon">
                            <g id="surface1">
                                <path d="M 11.914062 0 C 5.328125 0 0 5.5 0 12.304688 C 0 17.742188 3.414062 22.347656 8.148438 23.976562 C 8.738281 24.101562 8.957031 23.710938 8.957031 23.386719 C 8.957031 23.101562 8.9375 22.125 8.9375 21.105469 C 5.621094 21.835938 4.933594 19.636719 4.933594 19.636719 C 4.398438 18.210938 3.609375 17.84375 3.609375 17.84375 C 2.523438 17.09375 3.6875 17.09375 3.6875 17.09375 C 4.890625 17.171875 5.523438 18.355469 5.523438 18.355469 C 6.589844 20.226562 8.304688 19.699219 8.996094 19.375 C 9.09375 18.578125 9.410156 18.027344 9.746094 17.722656 C 7.101562 17.4375 4.320312 16.378906 4.320312 11.652344 C 4.320312 10.308594 4.792969 9.207031 5.542969 8.351562 C 5.425781 8.046875 5.011719 6.78125 5.664062 5.09375 C 5.664062 5.09375 6.667969 4.765625 8.9375 6.355469 C 9.90625 6.085938 10.910156 5.949219 11.914062 5.949219 C 12.921875 5.949219 13.945312 6.089844 14.894531 6.355469 C 17.164062 4.765625 18.167969 5.09375 18.167969 5.09375 C 18.820312 6.78125 18.40625 8.046875 18.289062 8.351562 C 19.058594 9.207031 19.511719 10.308594 19.511719 11.652344 C 19.511719 16.378906 16.730469 17.417969 14.066406 17.722656 C 14.5 18.109375 14.875 18.84375 14.875 20.003906 C 14.875 21.65625 14.855469 22.976562 14.855469 23.386719 C 14.855469 23.710938 15.074219 24.101562 15.664062 23.976562 C 20.398438 22.347656 23.8125 17.742188 23.8125 12.304688 C 23.832031 5.5 18.484375 0 11.914062 0 Z M 11.914062 0 "/>
                            </g>
                        </svg>
                """,
            link="https://github.com/JumpsuitCommerce/",
        ),
    },
    # "logo_light": "_static/kobitonlogo.jpg",
    # "logo_dark": "_static/kobitonlogo.jpg",
    "main_nav_links": {
        "kobiton.com":"https://kobiton.com/",
        "Documentation":"https://docs.kobiton.com/",
        "API Changelog":"changelogs/apichangelog",
        "Glossary":"glossary/glossary"
    },
    "show_prev_next": True,
    "show_scrolltop": True,
}

html_show_sphinx = False

# html_logo = '_static/logo2.png'

html_permalinks_icon = "<span>#</span>"

html_show_sourcelink = False

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

html_css_files = ["custom.css"]

#Favicon
html_favicon = '_static/synmax-favicon.png'

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Hyperion_API_Docs'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Hyperion_API_Docs.tex', u'Hyperion\\_API\\_Docs Documentation',
     u'Aalap Davjekar', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'hyperion_api_docs', u'Hyperion_API_Docs Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Hyperion_API_Docs', u'Hyperion API Documentation',
     author, 'Hyperion_API_Docs', "API Documentation for SynMax's Hyperion Client",
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------
